/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as NSHx26RouteImport } from './routes/NSHx26'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NSHx26WinnersRouteImport } from './routes/NSHx26.winners'
import { Route as NSHx26PicturesRouteImport } from './routes/NSHx26.pictures'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const NSHx26Route = NSHx26RouteImport.update({
  id: '/NSHx26',
  path: '/NSHx26',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NSHx26WinnersRoute = NSHx26WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => NSHx26Route,
} as any)
const NSHx26PicturesRoute = NSHx26PicturesRouteImport.update({
  id: '/pictures',
  path: '/pictures',
  getParentRoute: () => NSHx26Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/NSHx26': typeof NSHx26RouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/prizes': typeof PrizesRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/NSHx26/pictures': typeof NSHx26PicturesRoute
  '/NSHx26/winners': typeof NSHx26WinnersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/NSHx26': typeof NSHx26RouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/prizes': typeof PrizesRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/NSHx26/pictures': typeof NSHx26PicturesRoute
  '/NSHx26/winners': typeof NSHx26WinnersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/NSHx26': typeof NSHx26RouteWithChildren
  '/get-involved': typeof GetInvolvedRoute
  '/prizes': typeof PrizesRoute
  '/schedule': typeof ScheduleRoute
  '/sponsors': typeof SponsorsRoute
  '/team': typeof TeamRoute
  '/NSHx26/pictures': typeof NSHx26PicturesRoute
  '/NSHx26/winners': typeof NSHx26WinnersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/NSHx26'
    | '/get-involved'
    | '/prizes'
    | '/schedule'
    | '/sponsors'
    | '/team'
    | '/NSHx26/pictures'
    | '/NSHx26/winners'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/NSHx26'
    | '/get-involved'
    | '/prizes'
    | '/schedule'
    | '/sponsors'
    | '/team'
    | '/NSHx26/pictures'
    | '/NSHx26/winners'
  id:
    | '__root__'
    | '/'
    | '/NSHx26'
    | '/get-involved'
    | '/prizes'
    | '/schedule'
    | '/sponsors'
    | '/team'
    | '/NSHx26/pictures'
    | '/NSHx26/winners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NSHx26Route: typeof NSHx26RouteWithChildren
  GetInvolvedRoute: typeof GetInvolvedRoute
  PrizesRoute: typeof PrizesRoute
  ScheduleRoute: typeof ScheduleRoute
  SponsorsRoute: typeof SponsorsRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NSHx26': {
      id: '/NSHx26'
      path: '/NSHx26'
      fullPath: '/NSHx26'
      preLoaderRoute: typeof NSHx26RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NSHx26/winners': {
      id: '/NSHx26/winners'
      path: '/winners'
      fullPath: '/NSHx26/winners'
      preLoaderRoute: typeof NSHx26WinnersRouteImport
      parentRoute: typeof NSHx26Route
    }
    '/NSHx26/pictures': {
      id: '/NSHx26/pictures'
      path: '/pictures'
      fullPath: '/NSHx26/pictures'
      preLoaderRoute: typeof NSHx26PicturesRouteImport
      parentRoute: typeof NSHx26Route
    }
  }
}

interface NSHx26RouteChildren {
  NSHx26PicturesRoute: typeof NSHx26PicturesRoute
  NSHx26WinnersRoute: typeof NSHx26WinnersRoute
}

const NSHx26RouteChildren: NSHx26RouteChildren = {
  NSHx26PicturesRoute: NSHx26PicturesRoute,
  NSHx26WinnersRoute: NSHx26WinnersRoute,
}

const NSHx26RouteWithChildren =
  NSHx26Route._addFileChildren(NSHx26RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NSHx26Route: NSHx26RouteWithChildren,
  GetInvolvedRoute: GetInvolvedRoute,
  PrizesRoute: PrizesRoute,
  ScheduleRoute: ScheduleRoute,
  SponsorsRoute: SponsorsRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
